// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function SaveFile(arg1:main.FileData):Promise<void>;

export function SelectFolder():Promise<main.FileData>;
